--- # Define the ConfigMap for MySQL Database configuration
apiVersion : v1
kind : ConfigMap
metadata:
  name : db-config
data:
  host : mysql
  dbName: customer_service


--- # Define the Secret for MySQL Database configuration
apiVersion : v1
kind : Secret
metadata:
  name : db-secrets
data:
  username : cm9vdA==
  password : cm9vdA==

