#Server and servlet configuration
server:
  port: 8080
  servlet:
    contextPath: /

# Data Source Configuration
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_DB_HOST}/${MYSQL_DB_NAME_CUSTOMER_SERVICE}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}

# JPA Configuration
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
          enable_lazy_load_no_trans: true
          ddl-auto: update
      show-sql: true

