apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvcdemo-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mvcdemo
      tier: front-end
  template:
    metadata:
      labels:
        app: mvcdemo
        tier: front-end
    spec:
      containers:
      - name: mvcdemo-container
        image: techeduhub/mvcdemo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:   
        - name: MYSQL_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: hostName
        - name: MYSQL_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: portNumber
        - name: MYSQL_DB_NAME_CUSTOMER_SERVICE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: databaseName
        - name: MYSQL_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password

--- # Define the Application NodePort service
apiVersion: v1
kind: Service
metadata:
  name: mvcdemo-service
spec:
  type: NodePort
  selector:
    app: mvcdemo
    tier: front-end
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001

    