--- # Define the PersistentVolume for mysql database
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /AppData
    type: Directory

--- # Define PersistentVolumeClaim for mysql database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim 
  labels:
    app: mysql
    tier: database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

--- # Define the ConfigMap for database
apiVersion : v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  host: mysql
  port: '3308'
  databasename : mytestdb

--- # Define the Secret for database
apiVersion : v1
kind : Secret
metadata:
  name : mysql-secrets
data:
  username : cm9vdA==
  password : cm9vdA==

--- # Define the Deployment for database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-pod
        image: mysql:8.0.36
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: databasename
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

--- # Define a Service to expose mysql to other services
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3308
      targetPort: 3306
  selector:
    app: mysql
    tier: database
