apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.pvc.metadata.name}}
  namespace: {{.Values.namespace.metadata.name}}
spec:
  accessModes:
    {{- toYaml .Values.pvc.spec.accessModes | nindent 8}}
  resources:
    requests:
      storage: {{.Values.pvc.spec.resources.requests.storage}}
