apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.metadata.name}}
  namespace: {{.Values.namespace.metadata.name}}
spec:
  type: {{.Values.service.spec.type}}
  ports:
    {{- toYaml .Values.service.spec.ports | nindent 8}}
  selector:
    {{- toYaml .Values.deployment.spec.selector.matchLabels | nindent 8}}
