# Namespace
namespace:
  metadata:
    name: myapps
    labels:
      name: mvcdemo

# ConfigMap
configmap:
  metadata:
    name: mysql-config
  data:
    hostName: mysql-service
    portNumber: '3308'
    databaseName: customer_service

# Secret
secret:
  metadata:
    name: mysql-secret
  data:
    username: cm9vdA==
    password: cm9vdA==

# PersistentVolume
pv:
  metadata:
    name: myapps-pv
  spec:
    accessModes:
      - ReadWriteMany
    capacity:
      storage: 4Gi
    hostPath:
      path: /AppData
      type: Directory

# PersistentVolumeClaim
pvc:
  metadata:
    name: mysql-pvc
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi

# Service
service:
  metadata:
    name: mvcdemo-service
  spec:
    type: NodePort
    ports:
      - port: 8080
        targetPort: 8080
        nodePort: 30001

# Deployment
deployment:
  metadata:
    name: mvcdemo-deployment
  spec:
    replicas: 1
    strategy:
      type: RollingUpdate
    selector:
      matchLabels:
        app: mvcdemo
        tier: front-end
    template:
      containers:
        name: mvcdemo-container
        image: techeduhub/mvcdemo:latest
        imagePullPolicy: Always
        ports:
          containerPort: 3306
        volumeMounts:
          name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: hostName
          - name: MYSQL_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: portNumber
          - name: MYSQL_DB_NAME_CUSTOMER_SERVICE
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: databaseName
          - name: MYSQL_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: username
          - name: MYSQL_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password